// Auto-generated by scripts/build-templates.ts — DO NOT EDIT
// Run `bun run build:templates` to regenerate.

export const templates: Record<string, Record<string, string>> = {
  "api/hono": {
    "src/app.ts.eta":
      'import { Hono } from "hono";\nimport { cors } from "hono/cors";\n\nconst app = new Hono()\n  .use("/*", cors())\n  .get("/health", (c) => c.json({ status: "ok" }))\n  .get("/hello/:name", (c) => {\n    const name = c.req.param("name");\n    return c.json({ greeting: `Hello ${name}!` });\n  });\n\nexport type AppType = typeof app;\nexport { app };\n',
    "src/index.ts.eta": 'export { app } from "./app";\nexport type { AppType } from "./app";\n',
  },
  "api/rest-nextjs": {
    "src/index.ts.eta": 'export { apiResponse, apiError, withHandler } from "./utils";\n',
    "src/utils.ts.eta":
      'import type { NextRequest } from "next/server";\n\nexport function apiResponse<T>(data: T, status = 200) {\n  return Response.json(data, { status });\n}\n\nexport function apiError(message: string, status = 400) {\n  return Response.json({ error: message }, { status });\n}\n\nexport function withHandler(\n  handler: (req: NextRequest) => Promise<Response>,\n) {\n  return async (req: NextRequest) => {\n    try {\n      return await handler(req);\n    } catch (error) {\n      console.error("[API Error]", error);\n      return apiError("Internal Server Error", 500);\n    }\n  };\n}\n',
  },
  "api/trpc": {
    "src/client.ts.eta":
      'import { createTRPCClient, httpBatchLink } from "@trpc/client";\nimport superjson from "superjson";\nimport type { AppRouter } from "./router";\n\nexport function createTRPCClientProxy(url: string) {\n  return createTRPCClient<AppRouter>({\n    links: [\n      httpBatchLink({\n        url,\n        transformer: superjson,\n      }),\n    ],\n  });\n}\n',
    "src/index.ts.eta": 'export type { AppRouter } from "./router";\n',
    "src/router.ts.eta":
      'import { z } from "zod";\nimport { createTRPCRouter, publicProcedure } from "./server";\n<% if (it.database && it.database.strategy !== \'none\') { %>\nimport { db } from "<%= it.scope %>/db";\n<% } %>\n\nexport const appRouter = createTRPCRouter({\n  hello: publicProcedure\n    .input(z.object({ name: z.string() }))\n    .query(({ input }) => {\n      return { greeting: `Hello ${input.name}!` };\n    }),\n});\n\nexport type AppRouter = typeof appRouter;\n',
    "src/server.ts.eta":
      'import { initTRPC } from "@trpc/server";\nimport superjson from "superjson";\n\nexport const createTRPCContext = async (opts: { headers: Headers }) => {\n  return {\n    ...opts,\n  };\n};\n\nconst t = initTRPC.context<typeof createTRPCContext>().create({\n  transformer: superjson,\n});\n\nexport const createCallerFactory = t.createCallerFactory;\nexport const createTRPCRouter = t.router;\nexport const publicProcedure = t.procedure;\n',
  },
  "app/astro": {
    "astro.config.mjs.eta":
      'import { defineConfig } from "astro/config";\n<% if (it.hasReactPackages) { %>import react from "@astrojs/react";\n<% } %>\nexport default defineConfig({<% if (it.hasReactPackages) { %>\n  integrations: [react()],<% } %>\n});\n',
    "src/layouts/Layout.astro.eta":
      '---\ninterface Props {\n  title: string;\n}\n\nconst { title } = Astro.props;\n---\n\n<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title>{title}</title>\n  </head>\n  <body>\n    <slot />\n  </body>\n</html>\n',
    "src/pages/index.astro.eta":
      '---\nimport Layout from "../layouts/Layout.astro";\n---\n\n<Layout title="<%= it.app.name %>">\n  <main>\n    <h1><%= it.app.name %></h1>\n  </main>\n</Layout>\n',
  },
  "app/hono-standalone": {
    "src/index.ts.eta":
      'deimport { serve } from "@hono/node-server";\n<% if (it.api.strategy === \'hono\') { %>import { app } from "<%= it.scope %>/api";\n<% } else { %>import { Hono } from "hono";\n<% } %>\nconst port = <%= it.app.port %>;\n\nconsole.log(`Server running on http://localhost:${port}`);\n\nserve({\n  fetch: <% if (it.api.strategy === \'hono\') { %>app<% } else { %>new Hono()\n  .get("/health", (c) => c.json({ status: "ok" }))<% } %>.fetch,\n  port,\n});\n',
  },
  "app/nextjs": {
    "next.config.ts.eta":
      'import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n',
    "postcss.config.mjs.eta":
      'export default {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n',
    "src/app/globals.css.eta":
      '<% if (it.css.framework === \'tailwind4\') { %>@import "tailwindcss";\n<% if (it.css.ui === \'shadcn\') { %>@import "tw-animate-css";\n<% } %><% for (const source of it.wiring.cssSourceDirectives) { %>@source "<%= source %>";\n<% } %><% const consumedUi = it.app.consumes.find(c => it.packages.find(p => p.name === c && p.producesCSS)); %><% if (consumedUi) { %>@import "<%= it.scope %>/<%= consumedUi %>/globals.css";\n<% } %>\n@custom-variant dark (&:is(.dark *));\n<% } else { %>/* Global styles */\n<% } %>\n',
    "src/app/layout.tsx.eta":
      'import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "<%= it.app.name %>",\n  description: "<%= it.app.name %> app",\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n',
    "src/app/page.tsx.eta":
      "export default function Home() {\n  return (\n    <main>\n      <h1><%= it.app.name %></h1>\n    </main>\n  );\n}\n",
  },
  "app/nextjs-api-only": {
    "src/app/api/health/route.ts.eta":
      'export function GET() {\n  return Response.json({ status: "ok" });\n}\n',
    "src/app/layout.tsx.eta":
      'export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n',
  },
  "app/remix": {
    "app/root.tsx.eta":
      'import {\n  Links,\n  Meta,\n  Outlet,\n  Scripts,\n  ScrollRestoration,\n} from "@remix-run/react";\n\nexport default function App() {\n  return (\n    <html lang="en">\n      <head>\n        <meta charSet="utf-8" />\n        <meta name="viewport" content="width=device-width, initial-scale=1" />\n        <Meta />\n        <Links />\n      </head>\n      <body>\n        <Outlet />\n        <ScrollRestoration />\n        <Scripts />\n      </body>\n    </html>\n  );\n}\n',
    "app/routes/_index.tsx.eta":
      'import type { MetaFunction } from "@remix-run/node";\n\nexport const meta: MetaFunction = () => {\n  return [\n    { title: "<%= it.app.name %>" },\n    { name: "description", content: "<%= it.app.name %> app" },\n  ];\n};\n\nexport default function Index() {\n  return (\n    <main>\n      <h1><%= it.app.name %></h1>\n    </main>\n  );\n}\n',
    "vite.config.ts.eta":
      'import { vitePlugin as remix } from "@remix-run/dev";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({\n  plugins: [remix()],\n});\n',
  },
  "app/sveltekit": {
    "src/app.html.eta":
      '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title><%= it.app.name %></title>\n    %sveltekit.head%\n  </head>\n  <body>\n    <div id="app">\n      %sveltekit.body%\n    </div>\n  </body>\n</html>\n',
    "src/routes/+layout.svelte.eta":
      "<script>\n  let { children } = $props();\n</script>\n\n{@render children()}\n",
    "src/routes/+page.svelte.eta": "<h1><%= it.app.name %></h1>\n",
    "svelte.config.js.eta":
      "import adapter from \"@sveltejs/adapter-auto\";\n\n/** @type {import('@sveltejs/kit').Config} */\nconst config = {\n  kit: {\n    adapter: adapter(),\n  },\n};\n\nexport default config;\n",
    "vite.config.ts.eta":
      'import { sveltekit } from "@sveltejs/kit/vite";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({\n  plugins: [sveltekit()],\n});\n',
  },
  "app/vite-react": {
    "src/App.tsx.eta":
      "export default function App() {\n  return (\n    <main>\n      <h1><%= it.app.name %></h1>\n    </main>\n  );\n}\n",
    "src/index.css.eta":
      '<% if (it.css.framework === \'tailwind4\') { %>@import "tailwindcss";\n<% if (it.css.ui === \'shadcn\') { %>@import "tw-animate-css";\n<% } %><% for (const source of it.wiring.cssSourceDirectives) { %>@source "<%= source %>";\n<% } %>\n@custom-variant dark (&:is(.dark *));\n<% } else { %>/* Global styles */\n<% } %>\n',
    "src/main.tsx.eta":
      'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\nimport "./index.css";\n\nReactDOM.createRoot(document.getElementById("root")!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);\n',
    "vite.config.ts.eta":
      'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({\n  plugins: [react()],\n});\n',
  },
  "auth/better-auth": {
    "src/client.ts.eta":
      'import { createAuthClient } from "better-auth/client";\n\nexport const authClient = createAuthClient();\n',
    "src/index.ts.eta":
      'export { auth } from "./server";\nexport { authClient } from "./client";\n',
    "src/middleware.ts.eta": 'export { auth as middleware } from "./server";\n',
    "src/server.ts.eta":
      'import { betterAuth } from "better-auth";\n\nexport const auth = betterAuth({\n  emailAndPassword: {\n    enabled: true,\n  },\n});\n',
  },
  "auth/clerk": {
    "src/client.ts.eta":
      'export { useUser, useAuth, useClerk, useSignIn, useSignUp } from "@clerk/nextjs";\n',
    "src/index.ts.eta":
      'export { auth, currentUser } from "@clerk/nextjs/server";\nexport { ClerkProvider, SignIn, SignUp, UserButton } from "@clerk/nextjs";\n',
    "src/middleware.ts.eta":
      'import { clerkMiddleware } from "@clerk/nextjs/server";\n\nexport default clerkMiddleware();\n\nexport const config = {\n  matcher: [\n    "/((?!_next|[^?]*\\\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",\n    "/(api|trpc)(.*)",\n  ],\n};\n',
    "src/server.ts.eta": 'export { auth, currentUser, clerkClient } from "@clerk/nextjs/server";\n',
  },
  "auth/lucia": {
    "src/client.ts.eta":
      "// Lucia is server-only — use server actions or API routes for auth\nexport {};\n",
    "src/index.ts.eta": 'export { lucia, validateRequest } from "./server";\n',
    "src/middleware.ts.eta":
      'import type { NextRequest, NextResponse } from "next/server";\n\nexport function authMiddleware(_request: NextRequest, _response: NextResponse) {\n  // Lucia validation happens in server components via validateRequest()\n  // Add custom middleware logic here if needed\n}\n',
    "src/server.ts.eta":
      'import { Lucia } from "lucia";\nimport { cookies } from "next/headers";\nimport { cache } from "react";\n\nconst adapter = {\n  // TODO: Configure adapter based on your database\n};\n\nexport const lucia = new Lucia(adapter as never, {\n  sessionCookie: {\n    expires: false,\n    attributes: {\n      secure: process.env.NODE_ENV === "production",\n    },\n  },\n});\n\nexport const validateRequest = cache(async () => {\n  const sessionId = (await cookies()).get(lucia.sessionCookieName)?.value ?? null;\n  if (!sessionId) return { user: null, session: null };\n  const result = await lucia.validateSession(sessionId);\n  return result;\n});\n\ndeclare module "lucia" {\n  interface Register {\n    Lucia: typeof lucia;\n  }\n}\n',
  },
  "auth/next-auth": {
    "src/client.ts.eta":
      'export { useSession, signIn, signOut, SessionProvider } from "next-auth/react";\n',
    "src/index.ts.eta": 'export { auth, handlers, signIn, signOut } from "./server";\n',
    "src/middleware.ts.eta": 'export { auth as middleware } from "./server";\n',
    "src/server.ts.eta":
      'import NextAuth from "next-auth";\n\nexport const { handlers, signIn, signOut, auth } = NextAuth({\n  providers: [],\n  callbacks: {\n    session({ session, token }) {\n      if (token.sub) session.user.id = token.sub;\n      return session;\n    },\n  },\n});\n',
  },
  "auth/supabase-auth": {
    "src/client.ts.eta":
      'import { createBrowserClient as createSupabaseBrowserClient } from "<%= it.scope %>/db";\n\nexport function createBrowserClient() {\n  return createSupabaseBrowserClient();\n}\n',
    "src/index.ts.eta":
      'export { getSession, getUser } from "./server";\nexport { createBrowserClient } from "./client";\n',
    "src/middleware.ts.eta":
      'import { createServerClient } from "@supabase/ssr";\nimport type { NextRequest, NextResponse } from "next/server";\n\nexport function updateSession(request: NextRequest, response: NextResponse) {\n  const supabase = createServerClient(\n    process.env.SUPABASE_URL!,\n    process.env.SUPABASE_ANON_KEY!,\n    {\n      cookies: {\n        getAll() {\n          return request.cookies.getAll();\n        },\n        setAll(cookies) {\n          for (const { name, value, options } of cookies) {\n            request.cookies.set(name, value);\n            response.cookies.set(name, value, options);\n          }\n        },\n      },\n    },\n  );\n\n  return supabase.auth.getUser();\n}\n',
    "src/server.ts.eta":
      'import { createClient } from "<%= it.scope %>/db";\n\nexport async function getSession(cookieStore: Parameters<typeof createClient>[0]) {\n  const supabase = createClient(cookieStore);\n  const { data: { session } } = await supabase.auth.getSession();\n  return session;\n}\n\nexport async function getUser(cookieStore: Parameters<typeof createClient>[0]) {\n  const supabase = createClient(cookieStore);\n  const { data: { user } } = await supabase.auth.getUser();\n  return user;\n}\n',
  },
  "db/drizzle": {
    "drizzle.config.ts.eta":
      'import { defineConfig } from "drizzle-kit";\n\nexport default defineConfig({\n  schema: "./src/schema.ts",\n  out: "./drizzle",\n  dialect: "<%= it.drizzleDialect %>",\n  dbCredentials: {\n    url: process.env.DATABASE_URL!,\n  },\n});\n',
    "src/client.ts.eta": "<%~ it.drizzleClientContent %>\n",
    "src/index.ts.eta": 'export * from "./schema";\nexport { db } from "./client";\n',
    "src/schema.ts.eta":
      'import { <%= it.drizzleSchemaImports %> } from "<%= it.drizzleSchemaModule %>";\n\nexport const posts = <%= it.drizzleTableFn %>("posts", {\n  id: <%= it.drizzleIdColumn %>,\n  title: varchar("title", { length: 255 }).notNull(),\n  content: text("content"),\n  createdAt: timestamp("created_at").defaultNow().notNull(),\n});\n',
  },
  "db/prisma": {
    "prisma/schema.prisma.eta":
      'generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\nmodel Post {\n  id        String   @id @default(cuid())\n  title     String\n  content   String?\n  createdAt DateTime @default(now()) @map("created_at")\n\n  @@map("posts")\n}\n',
    "src/client.ts.eta":
      'import { PrismaClient } from "@prisma/client";\n\nconst globalForPrisma = globalThis as unknown as {\n  prisma: PrismaClient | undefined;\n};\n\nexport const prisma =\n  globalForPrisma.prisma ??\n  new PrismaClient({\n    log: process.env.NODE_ENV === "development" ? ["query"] : [],\n  });\n\nif (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;\n',
    "src/index.ts.eta": 'export { prisma } from "./client";\n',
  },
  "db/supabase": {
    "src/client.ts.eta":
      'import { createBrowserClient as createClient } from "@supabase/ssr";\nimport type { Database } from "./types";\n\nexport function createBrowserClient() {\n  return createClient<Database>(\n    process.env.NEXT_PUBLIC_SUPABASE_URL!,\n    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,\n  );\n}\n',
    "src/index.ts.eta":
      'export { createClient } from "./server";\nexport { createBrowserClient } from "./client";\nexport type { Database } from "./types";\n',
    "src/server.ts.eta":
      'import { createServerClient } from "@supabase/ssr";\nimport type { Database } from "./types";\n\nexport function createClient(cookieStore: {\n  getAll: () => { name: string; value: string }[];\n  set: (name: string, value: string, options: Record<string, unknown>) => void;\n}) {\n  return createServerClient<Database>(\n    process.env.SUPABASE_URL!,\n    process.env.SUPABASE_ANON_KEY!,\n    {\n      cookies: {\n        getAll() {\n          return cookieStore.getAll();\n        },\n        setAll(cookies) {\n          for (const { name, value, options } of cookies) {\n            cookieStore.set(name, value, options);\n          }\n        },\n      },\n    },\n  );\n}\n',
    "src/types.ts.eta":
      "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\nexport interface Database {\n  public: {\n    Tables: Record<string, never>;\n    Views: Record<string, never>;\n    Functions: Record<string, never>;\n    Enums: Record<string, never>;\n  };\n}\n",
  },
  "integration/ai/langchain": {
    "src/index.ts.eta": "// LangChain setup — configure your chain here\nexport {};\n",
  },
  "integration/ai/vercel-ai-sdk": {
    "src/client.ts.eta":
      'import { generateText as aiGenerateText, streamText as aiStreamText } from "ai";\nimport { openai } from "@ai-sdk/openai";\n\nexport async function generateText(prompt: string, model = "gpt-4o-mini") {\n  const { text } = await aiGenerateText({\n    model: openai(model),\n    prompt,\n  });\n  return text;\n}\n\nexport function streamText(prompt: string, model = "gpt-4o-mini") {\n  return aiStreamText({\n    model: openai(model),\n    prompt,\n  });\n}\n',
    "src/index.ts.eta": 'export { generateText, streamText } from "./client";\n',
  },
  "integration/analytics/plausible": {
    "src/client.ts.eta":
      'export function trackEvent(event: string, props?: Record<string, string | number | boolean>) {\n  if (typeof window !== "undefined" && (window as Record<string, unknown>).plausible) {\n    (window as Record<string, (...args: unknown[]) => void>).plausible(event, { props });\n  }\n}\n',
    "src/index.ts.eta":
      'export { PlausibleProvider } from "./provider";\nexport { trackEvent } from "./client";\n',
    "src/provider.tsx.eta":
      '"use client";\n\nimport Script from "next/script";\n\nexport function PlausibleProvider({ domain }: { domain: string }) {\n  return (\n    <Script\n      defer\n      data-domain={domain}\n      src="https://plausible.io/js/script.js"\n    />\n  );\n}\n',
    "src/server.ts.eta":
      "// Plausible is client-side only — use the Events API for server-side tracking\n// See: https://plausible.io/docs/events-api\nexport {};\n",
  },
  "integration/analytics/posthog": {
    "src/client.ts.eta":
      'import posthog from "posthog-js";\n\nexport function trackEvent(event: string, properties?: Record<string, unknown>) {\n  posthog.capture(event, properties);\n}\n\nexport function identifyUser(userId: string, traits?: Record<string, unknown>) {\n  posthog.identify(userId, traits);\n}\n',
    "src/index.ts.eta":
      'export { PostHogProvider } from "./provider";\nexport { trackEvent } from "./client";\n',
    "src/provider.tsx.eta":
      '"use client";\n\nimport posthog from "posthog-js";\nimport { PostHogProvider as PHProvider } from "posthog-js/react";\nimport { useEffect } from "react";\n\nexport function PostHogProvider({ children }: { children: React.ReactNode }) {\n  useEffect(() => {\n    posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {\n      api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,\n      capture_pageview: false,\n    });\n  }, []);\n\n  return <PHProvider client={posthog}>{children}</PHProvider>;\n}\n',
    "src/server.ts.eta":
      'import { PostHog } from "posthog-node";\n\nlet client: PostHog | null = null;\n\nfunction getClient(): PostHog {\n  if (!client) {\n    client = new PostHog(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {\n      host: process.env.NEXT_PUBLIC_POSTHOG_HOST,\n    });\n  }\n  return client;\n}\n\nexport function trackServerEvent(\n  distinctId: string,\n  event: string,\n  properties?: Record<string, unknown>,\n) {\n  getClient().capture({ distinctId, event, properties });\n}\n\nexport async function shutdown() {\n  await getClient().shutdown();\n}\n',
  },
  "integration/analytics/vercel-analytics": {
    "src/index.ts.eta":
      'export { Analytics } from "@vercel/analytics/react";\nexport { track } from "@vercel/analytics";\n',
    "src/server.ts.eta": 'export { track } from "@vercel/analytics/server";\n',
  },
  "integration/email/nodemailer": {
    "src/client.ts.eta":
      'import nodemailer from "nodemailer";\n\nconst transporter = nodemailer.createTransport({\n  host: process.env.SMTP_HOST,\n  port: Number(process.env.SMTP_PORT ?? 587),\n  secure: process.env.SMTP_SECURE === "true",\n  auth: {\n    user: process.env.SMTP_USER,\n    pass: process.env.SMTP_PASS,\n  },\n});\n\nexport async function sendEmail({\n  to,\n  subject,\n  html,\n  text,\n}: {\n  to: string | string[];\n  subject: string;\n  html?: string;\n  text?: string;\n}) {\n  return transporter.sendMail({\n    from: process.env.EMAIL_FROM ?? "noreply@example.com",\n    to: Array.isArray(to) ? to.join(", ") : to,\n    subject,\n    html,\n    text,\n  });\n}\n',
    "src/index.ts.eta": 'export { sendEmail } from "./client";\n',
  },
  "integration/email/react-email-resend": {
    "src/client.ts.eta":
      'import { Resend } from "resend";\n\nconst resend = new Resend(process.env.RESEND_API_KEY);\n\nexport async function sendEmail({\n  to,\n  subject,\n  react,\n}: {\n  to: string | string[];\n  subject: string;\n  react: React.ReactElement;\n}) {\n  const { data, error } = await resend.emails.send({\n    from: process.env.EMAIL_FROM ?? "noreply@example.com",\n    to,\n    subject,\n    react,\n  });\n\n  if (error) throw new Error(error.message);\n  return data;\n}\n',
    "src/index.ts.eta":
      'export { sendEmail } from "./client";\nexport { WelcomeEmail } from "./templates/welcome";\n',
    "src/templates/welcome.tsx.eta":
      'import { Html, Head, Body, Container, Text, Heading } from "@react-email/components";\n\ninterface WelcomeEmailProps {\n  name: string;\n}\n\nexport function WelcomeEmail({ name }: WelcomeEmailProps) {\n  return (\n    <Html>\n      <Head />\n      <Body style={{ fontFamily: "sans-serif" }}>\n        <Container>\n          <Heading>Welcome, {name}!</Heading>\n          <Text>Thanks for signing up. We\'re excited to have you.</Text>\n        </Container>\n      </Body>\n    </Html>\n  );\n}\n',
  },
  "integration/monitoring/sentry": {
    "src/index.ts.eta":
      'export { initSentry, captureException, captureMessage } from "./sentry";\n',
    "src/sentry.client.config.ts.eta":
      'import * as Sentry from "@sentry/nextjs";\n\nSentry.init({\n  dsn: process.env.SENTRY_DSN,\n  tracesSampleRate: 1.0,\n  replaysSessionSampleRate: 0.1,\n  replaysOnErrorSampleRate: 1.0,\n});\n',
    "src/sentry.server.config.ts.eta":
      'import * as Sentry from "@sentry/nextjs";\n\nSentry.init({\n  dsn: process.env.SENTRY_DSN,\n  tracesSampleRate: 1.0,\n});\n',
    "src/sentry.ts.eta":
      'import * as Sentry from "@sentry/nextjs";\n\nexport function initSentry() {\n  Sentry.init({\n    dsn: process.env.SENTRY_DSN,\n    tracesSampleRate: 1.0,\n    debug: process.env.NODE_ENV === "development",\n  });\n}\n\nexport function captureException(error: unknown, context?: Record<string, unknown>) {\n  Sentry.captureException(error, { extra: context });\n}\n\nexport function captureMessage(message: string, level: Sentry.SeverityLevel = "info") {\n  Sentry.captureMessage(message, level);\n}\n',
  },
  "integration/rate-limit/upstash": {
    "src/index.ts.eta":
      'import { Ratelimit } from "@upstash/ratelimit";\nimport { Redis } from "@upstash/redis";\n\nconst redis = new Redis({\n  url: process.env.UPSTASH_REDIS_REST_URL!,\n  token: process.env.UPSTASH_REDIS_REST_TOKEN!,\n});\n\n/**\n * Default rate limiter: 10 requests per 10 seconds using sliding window.\n */\nexport const ratelimit = new Ratelimit({\n  redis,\n  limiter: Ratelimit.slidingWindow(10, "10 s"),\n  analytics: true,\n});\n\n/**\n * Check rate limit by identifier (e.g. IP address, user ID).\n */\nexport async function checkRateLimit(identifier: string) {\n  const { success, limit, remaining, reset } = await ratelimit.limit(identifier);\n  return { success, limit, remaining, reset };\n}\n',
  },
  root: {
    "env.example.eta":
      "<% for (const v of it.envVars) { %>\n# <%= v.description %>\n<%= v.name %>=<%= v.example %>\n\n<% } %>\n",
    "gitignore.eta":
      "node_modules\n.turbo\n.next\ndist\nout\nbuild\n.env\n.env.local\n.env.*.local\n*.tsbuildinfo\n.DS_Store\ncoverage\n",
    "npmrc.eta": "auto-install-peers=true\n",
  },
};
