// Auto-generated by scripts/build-templates.ts — DO NOT EDIT
// Run `bun run build:templates` to regenerate.

export const templates: Record<string, Record<string, string>> = {
  "api/hono": {
    "src/app.ts.eta": "import { Hono } from \"hono\";\r\nimport { cors } from \"hono/cors\";\r\n\r\nconst app = new Hono()\r\n  .use(\"/*\", cors())\r\n  .get(\"/health\", (c) => c.json({ status: \"ok\" }))\r\n  .get(\"/hello/:name\", (c) => {\r\n    const name = c.req.param(\"name\");\r\n    return c.json({ greeting: `Hello ${name}!` });\r\n  });\r\n\r\nexport type AppType = typeof app;\r\nexport { app };\r\n",
    "src/index.ts.eta": "export { app } from \"./app\";\r\nexport type { AppType } from \"./app\";\r\n",
  },
  "api/rest-nextjs": {
    "src/index.ts.eta": "export { apiResponse, apiError, withHandler } from \"./utils\";\r\n",
    "src/utils.ts.eta": "import type { NextRequest } from \"next/server\";\r\n\r\nexport function apiResponse<T>(data: T, status = 200) {\r\n  return Response.json(data, { status });\r\n}\r\n\r\nexport function apiError(message: string, status = 400) {\r\n  return Response.json({ error: message }, { status });\r\n}\r\n\r\nexport function withHandler(\r\n  handler: (req: NextRequest) => Promise<Response>,\r\n) {\r\n  return async (req: NextRequest) => {\r\n    try {\r\n      return await handler(req);\r\n    } catch (error) {\r\n      console.error(\"[API Error]\", error);\r\n      return apiError(\"Internal Server Error\", 500);\r\n    }\r\n  };\r\n}\r\n",
  },
  "api/trpc": {
    "src/client.ts.eta": "import { createTRPCClient, httpBatchLink } from \"@trpc/client\";\r\nimport superjson from \"superjson\";\r\nimport type { AppRouter } from \"./router\";\r\n\r\nexport function createTRPCClientProxy(url: string) {\r\n  return createTRPCClient<AppRouter>({\r\n    links: [\r\n      httpBatchLink({\r\n        url,\r\n        transformer: superjson,\r\n      }),\r\n    ],\r\n  });\r\n}\r\n",
    "src/index.ts.eta": "export type { AppRouter } from \"./router\";\r\n",
    "src/router.ts.eta": "import { z } from \"zod\";\r\nimport { createTRPCRouter, publicProcedure } from \"./server\";\r\n<% if (it.database && it.database.strategy !== 'none') { %>\r\nimport { db } from \"<%= it.scope %>/db\";\r\n<% } %>\r\n\r\nexport const appRouter = createTRPCRouter({\r\n  hello: publicProcedure\r\n    .input(z.object({ name: z.string() }))\r\n    .query(({ input }) => {\r\n      return { greeting: `Hello ${input.name}!` };\r\n    }),\r\n});\r\n\r\nexport type AppRouter = typeof appRouter;\r\n",
    "src/server.ts.eta": "import { initTRPC } from \"@trpc/server\";\r\nimport superjson from \"superjson\";\r\n\r\nexport const createTRPCContext = async (opts: { headers: Headers }) => {\r\n  return {\r\n    ...opts,\r\n  };\r\n};\r\n\r\nconst t = initTRPC.context<typeof createTRPCContext>().create({\r\n  transformer: superjson,\r\n});\r\n\r\nexport const createCallerFactory = t.createCallerFactory;\r\nexport const createTRPCRouter = t.router;\r\nexport const publicProcedure = t.procedure;\r\n",
  },
  "app/astro": {
    "astro.config.mjs.eta": "import { defineConfig } from \"astro/config\";\r\n<% if (it.hasReactPackages) { %>import react from \"@astrojs/react\";\r\n<% } %>\r\nexport default defineConfig({<% if (it.hasReactPackages) { %>\r\n  integrations: [react()],<% } %>\r\n});\r\n",
    "src/layouts/Layout.astro.eta": "---\r\ninterface Props {\r\n  title: string;\r\n}\r\n\r\nconst { title } = Astro.props;\r\n---\r\n\r\n<!doctype html>\r\n<html lang=\"en\">\r\n  <head>\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n    <title>{title}</title>\r\n  </head>\r\n  <body>\r\n    <slot />\r\n  </body>\r\n</html>\r\n",
    "src/pages/index.astro.eta": "---\r\nimport Layout from \"../layouts/Layout.astro\";\r\n---\r\n\r\n<Layout title=\"<%= it.app.name %>\">\r\n  <main>\r\n    <h1><%= it.app.name %></h1>\r\n  </main>\r\n</Layout>\r\n",
  },
  "app/hono-standalone": {
    "src/index.ts.eta": "deimport { serve } from \"@hono/node-server\";\r\n<% if (it.api.strategy === 'hono') { %>import { app } from \"<%= it.scope %>/api\";\r\n<% } else { %>import { Hono } from \"hono\";\r\n<% } %>\r\nconst port = <%= it.app.port %>;\r\n\r\nconsole.log(`Server running on http://localhost:${port}`);\r\n\r\nserve({\r\n  fetch: <% if (it.api.strategy === 'hono') { %>app<% } else { %>new Hono()\r\n  .get(\"/health\", (c) => c.json({ status: \"ok\" }))<% } %>.fetch,\r\n  port,\r\n});\r\n",
  },
  "app/nextjs": {
    "next.config.ts.eta": "import type { NextConfig } from \"next\";\r\n\r\nconst nextConfig: NextConfig = {};\r\n\r\nexport default nextConfig;\r\n",
    "postcss.config.mjs.eta": "export default {\r\n  plugins: {\r\n    \"@tailwindcss/postcss\": {},\r\n  },\r\n};\r\n",
    "src/app/globals.css.eta": "<% if (it.css.framework === 'tailwind4') { %>@import \"tailwindcss\";\r\n<% if (it.css.ui === 'shadcn') { %>@import \"tw-animate-css\";\r\n<% } %><% for (const source of it.wiring.cssSourceDirectives) { %>@source \"<%= source %>\";\r\n<% } %><% const consumedUi = it.app.consumes.find(c => it.packages.find(p => p.name === c && p.producesCSS)); %><% if (consumedUi) { %>@import \"<%= it.scope %>/<%= consumedUi %>/globals.css\";\r\n<% } %>\r\n@custom-variant dark (&:is(.dark *));\r\n<% } else { %>/* Global styles */\r\n<% } %>\r\n",
    "src/app/layout.tsx.eta": "import type { Metadata } from \"next\";\r\nimport \"./globals.css\";\r\n\r\nexport const metadata: Metadata = {\r\n  title: \"<%= it.app.name %>\",\r\n  description: \"<%= it.app.name %> app\",\r\n};\r\n\r\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\r\n  return (\r\n    <html lang=\"en\">\r\n      <body>{children}</body>\r\n    </html>\r\n  );\r\n}\r\n",
    "src/app/page.tsx.eta": "export default function Home() {\r\n  return (\r\n    <main>\r\n      <h1><%= it.app.name %></h1>\r\n    </main>\r\n  );\r\n}\r\n",
  },
  "app/nextjs-api-only": {
    "src/app/api/health/route.ts.eta": "export function GET() {\r\n  return Response.json({ status: \"ok\" });\r\n}\r\n",
    "src/app/layout.tsx.eta": "export default function RootLayout({ children }: { children: React.ReactNode }) {\r\n  return (\r\n    <html lang=\"en\">\r\n      <body>{children}</body>\r\n    </html>\r\n  );\r\n}\r\n",
  },
  "app/remix": {
    "app/root.tsx.eta": "import {\r\n  Links,\r\n  Meta,\r\n  Outlet,\r\n  Scripts,\r\n  ScrollRestoration,\r\n} from \"@remix-run/react\";\r\n\r\nexport default function App() {\r\n  return (\r\n    <html lang=\"en\">\r\n      <head>\r\n        <meta charSet=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n        <Meta />\r\n        <Links />\r\n      </head>\r\n      <body>\r\n        <Outlet />\r\n        <ScrollRestoration />\r\n        <Scripts />\r\n      </body>\r\n    </html>\r\n  );\r\n}\r\n",
    "app/routes/_index.tsx.eta": "import type { MetaFunction } from \"@remix-run/node\";\r\n\r\nexport const meta: MetaFunction = () => {\r\n  return [\r\n    { title: \"<%= it.app.name %>\" },\r\n    { name: \"description\", content: \"<%= it.app.name %> app\" },\r\n  ];\r\n};\r\n\r\nexport default function Index() {\r\n  return (\r\n    <main>\r\n      <h1><%= it.app.name %></h1>\r\n    </main>\r\n  );\r\n}\r\n",
    "vite.config.ts.eta": "import { vitePlugin as remix } from \"@remix-run/dev\";\r\nimport { defineConfig } from \"vite\";\r\n\r\nexport default defineConfig({\r\n  plugins: [remix()],\r\n});\r\n",
  },
  "app/sveltekit": {
    "src/app.html.eta": "<!doctype html>\r\n<html lang=\"en\">\r\n  <head>\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n    <title><%= it.app.name %></title>\r\n    %sveltekit.head%\r\n  </head>\r\n  <body>\r\n    <div id=\"app\">\r\n      %sveltekit.body%\r\n    </div>\r\n  </body>\r\n</html>\r\n",
    "src/routes/+layout.svelte.eta": "<script>\r\n  let { children } = $props();\r\n</script>\r\n\r\n{@render children()}\r\n",
    "src/routes/+page.svelte.eta": "<h1><%= it.app.name %></h1>\r\n",
    "svelte.config.js.eta": "import adapter from \"@sveltejs/adapter-auto\";\r\n\r\n/** @type {import('@sveltejs/kit').Config} */\r\nconst config = {\r\n  kit: {\r\n    adapter: adapter(),\r\n  },\r\n};\r\n\r\nexport default config;\r\n",
    "vite.config.ts.eta": "import { sveltekit } from \"@sveltejs/kit/vite\";\r\nimport { defineConfig } from \"vite\";\r\n\r\nexport default defineConfig({\r\n  plugins: [sveltekit()],\r\n});\r\n",
  },
  "app/vite-react": {
    "src/App.tsx.eta": "export default function App() {\r\n  return (\r\n    <main>\r\n      <h1><%= it.app.name %></h1>\r\n    </main>\r\n  );\r\n}\r\n",
    "src/index.css.eta": "<% if (it.css.framework === 'tailwind4') { %>@import \"tailwindcss\";\r\n<% if (it.css.ui === 'shadcn') { %>@import \"tw-animate-css\";\r\n<% } %><% for (const source of it.wiring.cssSourceDirectives) { %>@source \"<%= source %>\";\r\n<% } %>\r\n@custom-variant dark (&:is(.dark *));\r\n<% } else { %>/* Global styles */\r\n<% } %>\r\n",
    "src/main.tsx.eta": "import React from \"react\";\r\nimport ReactDOM from \"react-dom/client\";\r\nimport App from \"./App\";\r\nimport \"./index.css\";\r\n\r\nReactDOM.createRoot(document.getElementById(\"root\")!).render(\r\n  <React.StrictMode>\r\n    <App />\r\n  </React.StrictMode>,\r\n);\r\n",
    "vite.config.ts.eta": "import react from \"@vitejs/plugin-react\";\r\nimport { defineConfig } from \"vite\";\r\n\r\nexport default defineConfig({\r\n  plugins: [react()],\r\n});\r\n",
  },
  "auth/better-auth": {
    "src/client.ts.eta": "import { createAuthClient } from \"better-auth/client\";\r\n\r\nexport const authClient = createAuthClient();\r\n",
    "src/index.ts.eta": "export { auth } from \"./server\";\r\nexport { authClient } from \"./client\";\r\n",
    "src/middleware.ts.eta": "export { auth as middleware } from \"./server\";\r\n",
    "src/server.ts.eta": "import { betterAuth } from \"better-auth\";\r\n\r\nexport const auth = betterAuth({\r\n  emailAndPassword: {\r\n    enabled: true,\r\n  },\r\n});\r\n",
  },
  "auth/clerk": {
    "src/client.ts.eta": "export { useUser, useAuth, useClerk, useSignIn, useSignUp } from \"@clerk/nextjs\";\r\n",
    "src/index.ts.eta": "export { auth, currentUser } from \"@clerk/nextjs/server\";\r\nexport { ClerkProvider, SignIn, SignUp, UserButton } from \"@clerk/nextjs\";\r\n",
    "src/middleware.ts.eta": "import { clerkMiddleware } from \"@clerk/nextjs/server\";\r\n\r\nexport default clerkMiddleware();\r\n\r\nexport const config = {\r\n  matcher: [\r\n    \"/((?!_next|[^?]*\\\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)\",\r\n    \"/(api|trpc)(.*)\",\r\n  ],\r\n};\r\n",
    "src/server.ts.eta": "export { auth, currentUser, clerkClient } from \"@clerk/nextjs/server\";\r\n",
  },
  "auth/lucia": {
    "src/client.ts.eta": "// Lucia is server-only — use server actions or API routes for auth\r\nexport {};\r\n",
    "src/index.ts.eta": "export { lucia, validateRequest } from \"./server\";\r\n",
    "src/middleware.ts.eta": "import type { NextRequest, NextResponse } from \"next/server\";\r\n\r\nexport function authMiddleware(_request: NextRequest, _response: NextResponse) {\r\n  // Lucia validation happens in server components via validateRequest()\r\n  // Add custom middleware logic here if needed\r\n}\r\n",
    "src/server.ts.eta": "import { Lucia } from \"lucia\";\r\nimport { cookies } from \"next/headers\";\r\nimport { cache } from \"react\";\r\n\r\nconst adapter = {\r\n  // TODO: Configure adapter based on your database\r\n};\r\n\r\nexport const lucia = new Lucia(adapter as never, {\r\n  sessionCookie: {\r\n    expires: false,\r\n    attributes: {\r\n      secure: process.env.NODE_ENV === \"production\",\r\n    },\r\n  },\r\n});\r\n\r\nexport const validateRequest = cache(async () => {\r\n  const sessionId = (await cookies()).get(lucia.sessionCookieName)?.value ?? null;\r\n  if (!sessionId) return { user: null, session: null };\r\n  const result = await lucia.validateSession(sessionId);\r\n  return result;\r\n});\r\n\r\ndeclare module \"lucia\" {\r\n  interface Register {\r\n    Lucia: typeof lucia;\r\n  }\r\n}\r\n",
  },
  "auth/next-auth": {
    "src/client.ts.eta": "export { useSession, signIn, signOut, SessionProvider } from \"next-auth/react\";\r\n",
    "src/index.ts.eta": "export { auth, handlers, signIn, signOut } from \"./server\";\r\n",
    "src/middleware.ts.eta": "export { auth as middleware } from \"./server\";\r\n",
    "src/server.ts.eta": "import NextAuth from \"next-auth\";\r\n\r\nexport const { handlers, signIn, signOut, auth } = NextAuth({\r\n  providers: [],\r\n  callbacks: {\r\n    session({ session, token }) {\r\n      if (token.sub) session.user.id = token.sub;\r\n      return session;\r\n    },\r\n  },\r\n});\r\n",
  },
  "auth/supabase-auth": {
    "src/client.ts.eta": "import { createBrowserClient as createSupabaseBrowserClient } from \"<%= it.scope %>/db\";\r\n\r\nexport function createBrowserClient() {\r\n  return createSupabaseBrowserClient();\r\n}\r\n",
    "src/index.ts.eta": "export { getSession, getUser } from \"./server\";\r\nexport { createBrowserClient } from \"./client\";\r\n",
    "src/middleware.ts.eta": "import { createServerClient } from \"@supabase/ssr\";\r\nimport type { NextRequest, NextResponse } from \"next/server\";\r\n\r\nexport function updateSession(request: NextRequest, response: NextResponse) {\r\n  const supabase = createServerClient(\r\n    process.env.SUPABASE_URL!,\r\n    process.env.SUPABASE_ANON_KEY!,\r\n    {\r\n      cookies: {\r\n        getAll() {\r\n          return request.cookies.getAll();\r\n        },\r\n        setAll(cookies) {\r\n          for (const { name, value, options } of cookies) {\r\n            request.cookies.set(name, value);\r\n            response.cookies.set(name, value, options);\r\n          }\r\n        },\r\n      },\r\n    },\r\n  );\r\n\r\n  return supabase.auth.getUser();\r\n}\r\n",
    "src/server.ts.eta": "import { createClient } from \"<%= it.scope %>/db\";\r\n\r\nexport async function getSession(cookieStore: Parameters<typeof createClient>[0]) {\r\n  const supabase = createClient(cookieStore);\r\n  const { data: { session } } = await supabase.auth.getSession();\r\n  return session;\r\n}\r\n\r\nexport async function getUser(cookieStore: Parameters<typeof createClient>[0]) {\r\n  const supabase = createClient(cookieStore);\r\n  const { data: { user } } = await supabase.auth.getUser();\r\n  return user;\r\n}\r\n",
  },
  "db/drizzle": {
    "drizzle.config.ts.eta": "import { defineConfig } from \"drizzle-kit\";\r\n\r\nexport default defineConfig({\r\n  schema: \"./src/schema.ts\",\r\n  out: \"./drizzle\",\r\n  dialect: \"<%= it.drizzleDialect %>\",\r\n  dbCredentials: {\r\n    url: process.env.DATABASE_URL!,\r\n  },\r\n});\r\n",
    "src/client.ts.eta": "<%~ it.drizzleClientContent %>\r\n",
    "src/index.ts.eta": "export * from \"./schema\";\r\nexport { db } from \"./client\";\r\n",
    "src/schema.ts.eta": "import { <%= it.drizzleSchemaImports %> } from \"<%= it.drizzleSchemaModule %>\";\r\n\r\nexport const posts = <%= it.drizzleTableFn %>(\"posts\", {\r\n  id: <%= it.drizzleIdColumn %>,\r\n  title: varchar(\"title\", { length: 255 }).notNull(),\r\n  content: text(\"content\"),\r\n  createdAt: timestamp(\"created_at\").defaultNow().notNull(),\r\n});\r\n",
  },
  "db/prisma": {
    "prisma/schema.prisma.eta": "generator client {\r\n  provider = \"prisma-client-js\"\r\n}\r\n\r\ndatasource db {\r\n  provider = \"postgresql\"\r\n  url      = env(\"DATABASE_URL\")\r\n}\r\n\r\nmodel Post {\r\n  id        String   @id @default(cuid())\r\n  title     String\r\n  content   String?\r\n  createdAt DateTime @default(now()) @map(\"created_at\")\r\n\r\n  @@map(\"posts\")\r\n}\r\n",
    "src/client.ts.eta": "import { PrismaClient } from \"@prisma/client\";\r\n\r\nconst globalForPrisma = globalThis as unknown as {\r\n  prisma: PrismaClient | undefined;\r\n};\r\n\r\nexport const prisma =\r\n  globalForPrisma.prisma ??\r\n  new PrismaClient({\r\n    log: process.env.NODE_ENV === \"development\" ? [\"query\"] : [],\r\n  });\r\n\r\nif (process.env.NODE_ENV !== \"production\") globalForPrisma.prisma = prisma;\r\n",
    "src/index.ts.eta": "export { prisma } from \"./client\";\r\n",
  },
  "db/supabase": {
    "src/client.ts.eta": "import { createBrowserClient as createClient } from \"@supabase/ssr\";\r\nimport type { Database } from \"./types\";\r\n\r\nexport function createBrowserClient() {\r\n  return createClient<Database>(\r\n    process.env.NEXT_PUBLIC_SUPABASE_URL!,\r\n    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,\r\n  );\r\n}\r\n",
    "src/index.ts.eta": "export { createClient } from \"./server\";\r\nexport { createBrowserClient } from \"./client\";\r\nexport type { Database } from \"./types\";\r\n",
    "src/server.ts.eta": "import { createServerClient } from \"@supabase/ssr\";\r\nimport type { Database } from \"./types\";\r\n\r\nexport function createClient(cookieStore: {\r\n  getAll: () => { name: string; value: string }[];\r\n  set: (name: string, value: string, options: Record<string, unknown>) => void;\r\n}) {\r\n  return createServerClient<Database>(\r\n    process.env.SUPABASE_URL!,\r\n    process.env.SUPABASE_ANON_KEY!,\r\n    {\r\n      cookies: {\r\n        getAll() {\r\n          return cookieStore.getAll();\r\n        },\r\n        setAll(cookies) {\r\n          for (const { name, value, options } of cookies) {\r\n            cookieStore.set(name, value, options);\r\n          }\r\n        },\r\n      },\r\n    },\r\n  );\r\n}\r\n",
    "src/types.ts.eta": "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\r\n\r\nexport interface Database {\r\n  public: {\r\n    Tables: Record<string, never>;\r\n    Views: Record<string, never>;\r\n    Functions: Record<string, never>;\r\n    Enums: Record<string, never>;\r\n  };\r\n}\r\n",
  },
  "integration/ai/langchain": {
    "src/index.ts.eta": "// LangChain setup — configure your chain here\r\nexport {};\r\n",
  },
  "integration/ai/vercel-ai-sdk": {
    "src/client.ts.eta": "import { generateText as aiGenerateText, streamText as aiStreamText } from \"ai\";\r\nimport { openai } from \"@ai-sdk/openai\";\r\n\r\nexport async function generateText(prompt: string, model = \"gpt-4o-mini\") {\r\n  const { text } = await aiGenerateText({\r\n    model: openai(model),\r\n    prompt,\r\n  });\r\n  return text;\r\n}\r\n\r\nexport function streamText(prompt: string, model = \"gpt-4o-mini\") {\r\n  return aiStreamText({\r\n    model: openai(model),\r\n    prompt,\r\n  });\r\n}\r\n",
    "src/index.ts.eta": "export { generateText, streamText } from \"./client\";\r\n",
  },
  "integration/analytics/plausible": {
    "src/client.ts.eta": "export function trackEvent(event: string, props?: Record<string, string | number | boolean>) {\r\n  if (typeof window !== \"undefined\" && (window as Record<string, unknown>).plausible) {\r\n    (window as Record<string, (...args: unknown[]) => void>).plausible(event, { props });\r\n  }\r\n}\r\n",
    "src/index.ts.eta": "export { PlausibleProvider } from \"./provider\";\r\nexport { trackEvent } from \"./client\";\r\n",
    "src/provider.tsx.eta": "\"use client\";\r\n\r\nimport Script from \"next/script\";\r\n\r\nexport function PlausibleProvider({ domain }: { domain: string }) {\r\n  return (\r\n    <Script\r\n      defer\r\n      data-domain={domain}\r\n      src=\"https://plausible.io/js/script.js\"\r\n    />\r\n  );\r\n}\r\n",
    "src/server.ts.eta": "// Plausible is client-side only — use the Events API for server-side tracking\r\n// See: https://plausible.io/docs/events-api\r\nexport {};\r\n",
  },
  "integration/analytics/posthog": {
    "src/client.ts.eta": "import posthog from \"posthog-js\";\r\n\r\nexport function trackEvent(event: string, properties?: Record<string, unknown>) {\r\n  posthog.capture(event, properties);\r\n}\r\n\r\nexport function identifyUser(userId: string, traits?: Record<string, unknown>) {\r\n  posthog.identify(userId, traits);\r\n}\r\n",
    "src/index.ts.eta": "export { PostHogProvider } from \"./provider\";\r\nexport { trackEvent } from \"./client\";\r\n",
    "src/provider.tsx.eta": "\"use client\";\r\n\r\nimport posthog from \"posthog-js\";\r\nimport { PostHogProvider as PHProvider } from \"posthog-js/react\";\r\nimport { useEffect } from \"react\";\r\n\r\nexport function PostHogProvider({ children }: { children: React.ReactNode }) {\r\n  useEffect(() => {\r\n    posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {\r\n      api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,\r\n      capture_pageview: false,\r\n    });\r\n  }, []);\r\n\r\n  return <PHProvider client={posthog}>{children}</PHProvider>;\r\n}\r\n",
    "src/server.ts.eta": "import { PostHog } from \"posthog-node\";\r\n\r\nlet client: PostHog | null = null;\r\n\r\nfunction getClient(): PostHog {\r\n  if (!client) {\r\n    client = new PostHog(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {\r\n      host: process.env.NEXT_PUBLIC_POSTHOG_HOST,\r\n    });\r\n  }\r\n  return client;\r\n}\r\n\r\nexport function trackServerEvent(\r\n  distinctId: string,\r\n  event: string,\r\n  properties?: Record<string, unknown>,\r\n) {\r\n  getClient().capture({ distinctId, event, properties });\r\n}\r\n\r\nexport async function shutdown() {\r\n  await getClient().shutdown();\r\n}\r\n",
  },
  "integration/analytics/vercel-analytics": {
    "src/index.ts.eta": "export { Analytics } from \"@vercel/analytics/react\";\r\nexport { track } from \"@vercel/analytics\";\r\n",
    "src/server.ts.eta": "export { track } from \"@vercel/analytics/server\";\r\n",
  },
  "integration/email/nodemailer": {
    "src/client.ts.eta": "import nodemailer from \"nodemailer\";\r\n\r\nconst transporter = nodemailer.createTransport({\r\n  host: process.env.SMTP_HOST,\r\n  port: Number(process.env.SMTP_PORT ?? 587),\r\n  secure: process.env.SMTP_SECURE === \"true\",\r\n  auth: {\r\n    user: process.env.SMTP_USER,\r\n    pass: process.env.SMTP_PASS,\r\n  },\r\n});\r\n\r\nexport async function sendEmail({\r\n  to,\r\n  subject,\r\n  html,\r\n  text,\r\n}: {\r\n  to: string | string[];\r\n  subject: string;\r\n  html?: string;\r\n  text?: string;\r\n}) {\r\n  return transporter.sendMail({\r\n    from: process.env.EMAIL_FROM ?? \"noreply@example.com\",\r\n    to: Array.isArray(to) ? to.join(\", \") : to,\r\n    subject,\r\n    html,\r\n    text,\r\n  });\r\n}\r\n",
    "src/index.ts.eta": "export { sendEmail } from \"./client\";\r\n",
  },
  "integration/email/react-email-resend": {
    "src/client.ts.eta": "import { Resend } from \"resend\";\r\n\r\nconst resend = new Resend(process.env.RESEND_API_KEY);\r\n\r\nexport async function sendEmail({\r\n  to,\r\n  subject,\r\n  react,\r\n}: {\r\n  to: string | string[];\r\n  subject: string;\r\n  react: React.ReactElement;\r\n}) {\r\n  const { data, error } = await resend.emails.send({\r\n    from: process.env.EMAIL_FROM ?? \"noreply@example.com\",\r\n    to,\r\n    subject,\r\n    react,\r\n  });\r\n\r\n  if (error) throw new Error(error.message);\r\n  return data;\r\n}\r\n",
    "src/index.ts.eta": "export { sendEmail } from \"./client\";\r\nexport { WelcomeEmail } from \"./templates/welcome\";\r\n",
    "src/templates/welcome.tsx.eta": "import { Html, Head, Body, Container, Text, Heading } from \"@react-email/components\";\r\n\r\ninterface WelcomeEmailProps {\r\n  name: string;\r\n}\r\n\r\nexport function WelcomeEmail({ name }: WelcomeEmailProps) {\r\n  return (\r\n    <Html>\r\n      <Head />\r\n      <Body style={{ fontFamily: \"sans-serif\" }}>\r\n        <Container>\r\n          <Heading>Welcome, {name}!</Heading>\r\n          <Text>Thanks for signing up. We're excited to have you.</Text>\r\n        </Container>\r\n      </Body>\r\n    </Html>\r\n  );\r\n}\r\n",
  },
  "integration/monitoring/sentry": {
    "src/index.ts.eta": "export { initSentry, captureException, captureMessage } from \"./sentry\";\r\n",
    "src/sentry.client.config.ts.eta": "import * as Sentry from \"@sentry/nextjs\";\r\n\r\nSentry.init({\r\n  dsn: process.env.SENTRY_DSN,\r\n  tracesSampleRate: 1.0,\r\n  replaysSessionSampleRate: 0.1,\r\n  replaysOnErrorSampleRate: 1.0,\r\n});\r\n",
    "src/sentry.server.config.ts.eta": "import * as Sentry from \"@sentry/nextjs\";\r\n\r\nSentry.init({\r\n  dsn: process.env.SENTRY_DSN,\r\n  tracesSampleRate: 1.0,\r\n});\r\n",
    "src/sentry.ts.eta": "import * as Sentry from \"@sentry/nextjs\";\r\n\r\nexport function initSentry() {\r\n  Sentry.init({\r\n    dsn: process.env.SENTRY_DSN,\r\n    tracesSampleRate: 1.0,\r\n    debug: process.env.NODE_ENV === \"development\",\r\n  });\r\n}\r\n\r\nexport function captureException(error: unknown, context?: Record<string, unknown>) {\r\n  Sentry.captureException(error, { extra: context });\r\n}\r\n\r\nexport function captureMessage(message: string, level: Sentry.SeverityLevel = \"info\") {\r\n  Sentry.captureMessage(message, level);\r\n}\r\n",
  },
  "integration/rate-limit/upstash": {
    "src/index.ts.eta": "import { Ratelimit } from \"@upstash/ratelimit\";\r\nimport { Redis } from \"@upstash/redis\";\r\n\r\nconst redis = new Redis({\r\n  url: process.env.UPSTASH_REDIS_REST_URL!,\r\n  token: process.env.UPSTASH_REDIS_REST_TOKEN!,\r\n});\r\n\r\n/**\r\n * Default rate limiter: 10 requests per 10 seconds using sliding window.\r\n */\r\nexport const ratelimit = new Ratelimit({\r\n  redis,\r\n  limiter: Ratelimit.slidingWindow(10, \"10 s\"),\r\n  analytics: true,\r\n});\r\n\r\n/**\r\n * Check rate limit by identifier (e.g. IP address, user ID).\r\n */\r\nexport async function checkRateLimit(identifier: string) {\r\n  const { success, limit, remaining, reset } = await ratelimit.limit(identifier);\r\n  return { success, limit, remaining, reset };\r\n}\r\n",
  },
  "root": {
    "env.example.eta": "<% for (const v of it.envVars) { %>\r\n# <%= v.description %>\r\n<%= v.name %>=<%= v.example %>\r\n\r\n<% } %>\r\n",
    "gitignore.eta": "node_modules\r\n.turbo\r\n.next\r\ndist\r\nout\r\nbuild\r\n.env\r\n.env.local\r\n.env.*.local\r\n*.tsbuildinfo\r\n.DS_Store\r\ncoverage\r\n",
    "npmrc.eta": "auto-install-peers=true\r\n",
  },
};
