/**
 * Build script for @create-turbo-stack/templates.
 *
 * Reads all .eta files from src/ and generates a templates-map.ts
 * that exports them as a Record<string, Record<string, string>>.
 *
 * Template key is derived from directory structure:
 *   src/app/nextjs/src/app/page.tsx.eta → key: "app/nextjs", file: "src/app/page.tsx.eta"
 *   src/root/gitignore.eta             → key: "root",       file: "gitignore.eta"
 *   src/db/drizzle/src/index.ts.eta    → key: "db/drizzle", file: "src/index.ts.eta"
 *
 * The first two path segments after src/ form the template key.
 * Special case: "integration" has 3 segments (integration/analytics/posthog).
 *
 * Usage: bun run scripts/build-templates.ts
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const SRC_DIR = join(import.meta.dirname, "..", "src");
const OUT_FILE = join(SRC_DIR, "templates-map.ts");

/**
 * Convention: directories whose name starts with `_` are reference /
 * example templates. They're excluded from the production bundle by
 * default — pass `--include-all` to include them.
 *
 * Why: `_TEMPLATE/` (and any future `_DRAFT/`, `_EXPERIMENTAL/`) live in
 * the source tree as discoverable copy-paste references but shouldn't
 * inflate the published `templates-map.ts` (which the browser builder
 * also imports). Using a filename convention beats commenting code out.
 */
const INCLUDE_ALL = process.argv.includes("--include-all");

function shouldSkipDir(name: string): boolean {
  if (INCLUDE_ALL) return false;
  return name.startsWith("_");
}

async function walkDir(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (shouldSkipDir(entry.name)) continue;
      files.push(...(await walkDir(join(dir, entry.name))));
    } else if (entry.name.endsWith(".eta")) {
      files.push(join(dir, entry.name));
    }
  }

  return files;
}

/**
 * Derive the template key from a file path relative to src/.
 *
 * Rules:
 * - "root/gitignore.eta" → key: "root", file: "gitignore.eta"
 * - "app/nextjs/src/app/page.tsx.eta" → key: "app/nextjs", file: "src/app/page.tsx.eta"
 * - "db/drizzle/src/index.ts.eta" → key: "db/drizzle", file: "src/index.ts.eta"
 * - "auth/clerk/src/index.ts.eta" → key: "auth/clerk", file: "src/index.ts.eta"
 * - "integration/analytics/posthog/src/index.ts.eta" → key: "integration/analytics/posthog", file: "src/index.ts.eta"
 */
function deriveKey(relPath: string): { key: string; file: string } {
  const parts = relPath.split(sep);
  const category = parts[0];

  // "root" is a single-segment category
  if (category === "root") {
    return { key: "root", file: parts.slice(1).join("/") };
  }

  // "integration" has 3 segments: integration/type/provider
  if (category === "integration" && parts.length >= 4) {
    return {
      key: parts.slice(0, 3).join("/"),
      file: parts.slice(3).join("/"),
    };
  }

  // Default: 2 segments (app/nextjs, db/drizzle, auth/clerk, api/trpc, etc.)
  if (parts.length >= 3) {
    return {
      key: parts.slice(0, 2).join("/"),
      file: parts.slice(2).join("/"),
    };
  }

  return { key: category, file: parts.slice(1).join("/") };
}

async function main() {
  const files = await walkDir(SRC_DIR);
  const templateMap: Record<string, Record<string, string>> = {};

  for (const file of files) {
    const relPath = relative(SRC_DIR, file);
    const { key, file: templateFile } = deriveKey(relPath);
    const content = await readFile(file, "utf-8");

    if (!templateMap[key]) {
      templateMap[key] = {};
    }
    templateMap[key][templateFile] = content;
  }

  // Sort keys for deterministic output
  const sortedKeys = Object.keys(templateMap).sort();

  const lines: string[] = [
    "// Auto-generated by scripts/build-templates.ts — DO NOT EDIT",
    "// Run `bun run build:templates` to regenerate.",
    "",
    "export const templates: Record<string, Record<string, string>> = {",
  ];

  for (const key of sortedKeys) {
    lines.push(`  ${JSON.stringify(key)}: {`);
    const fileKeys = Object.keys(templateMap[key]).sort();
    for (const fileKey of fileKeys) {
      const content = templateMap[key][fileKey];
      lines.push(`    ${JSON.stringify(fileKey)}: ${JSON.stringify(content)},`);
    }
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");

  await writeFile(OUT_FILE, lines.join("\n"), "utf-8");

  const totalFiles = files.length;
  const totalKeys = sortedKeys.length;
  console.log(`✓ Generated templates-map.ts: ${totalFiles} templates in ${totalKeys} categories`);
}

main().catch((err) => {
  console.error("Failed to build templates:", err);
  process.exit(1);
});
