import { randomBytes, toBase64url } from "{{scope}}/crypto";

export const CSP_HEADER = "Content-Security-Policy";
export const CSP_REPORT_ONLY_HEADER = "Content-Security-Policy-Report-Only";

/**
 * A single CSP source expression.
 * Examples: "'self'", "'none'", "'strict-dynamic'", "'nonce-abc123'",
 *           "https://cdn.example.com", "'sha256-xyz...'".
 */
export type CSPSource = string;

/**
 * Typed CSP directive map. Boolean directives (upgrade-insecure-requests,
 * block-all-mixed-content) are set with `true`; `false` or absence omits them.
 */
export interface CSPDirectives {
  "default-src"?: CSPSource[];
  "script-src"?: CSPSource[];
  "style-src"?: CSPSource[];
  "img-src"?: CSPSource[];
  "connect-src"?: CSPSource[];
  "font-src"?: CSPSource[];
  "media-src"?: CSPSource[];
  "object-src"?: CSPSource[];
  "frame-src"?: CSPSource[];
  "worker-src"?: CSPSource[];
  "child-src"?: CSPSource[];
  "manifest-src"?: CSPSource[];
  "frame-ancestors"?: CSPSource[];
  "base-uri"?: CSPSource[];
  "form-action"?: CSPSource[];
  sandbox?: CSPSource[];
  "report-uri"?: string[];
  "report-to"?: string[];
  "upgrade-insecure-requests"?: boolean;
  "block-all-mixed-content"?: boolean;
}

/**
 * Serializes a CSPDirectives object to a Content-Security-Policy header value string.
 * Directive ordering follows insertion order of the object.
 */
export function buildCSP(directives: CSPDirectives): string {
  const parts: string[] = [];

  for (const key of Object.keys(directives) as Array<keyof CSPDirectives>) {
    const value = directives[key];
    if (value === undefined) continue;
    if (typeof value === "boolean") {
      if (value) parts.push(key);
      continue;
    }
    if (value.length > 0) {
      parts.push(`${key} ${value.join(" ")}`);
    }
  }

  return parts.join("; ");
}

/**
 * Generates a cryptographically strong nonce for use in a CSP script-src directive.
 * Returns a base64url-encoded string (no padding). Each page load should get a fresh nonce.
 *
 * Uses randomBytes from @scope/crypto (CSPRNG via getRandomValues) — 16 bytes = 128 bits entropy.
 */
export function generateNonce(): string {
  return toBase64url(randomBytes(16));
}

/**
 * Builds a strict nonce-based CSP policy following the OWASP CSP Cheat Sheet.
 *
 * Why nonce + strict-dynamic?
 * Static source allowlists are fragile: a single compromised CDN or inline script
 * bypasses the policy entirely. Nonces cryptographically bind each allowed script
 * to the server response that generated it. `strict-dynamic` propagates trust to
 * scripts loaded by nonce-trusted scripts, enabling module-based applications
 * without listing every source. `unsafe-inline` and `unsafe-eval` are excluded.
 *
 * @param nonce - The nonce generated by generateNonce() for this response.
 * @param extra - Optional overrides/additions merged on top of the strict default.
 *                Passing a key overrides the default value for that directive.
 */
export function strictCspWithNonce(
  nonce: string,
  extra?: CSPDirectives,
): string {
  const base: CSPDirectives = {
    "default-src": ["'self'"],
    "script-src": [`'nonce-${nonce}'`, "'strict-dynamic'"],
    "style-src": ["'self'"],
    "img-src": ["'self'", "data:"],
    "connect-src": ["'self'"],
    "font-src": ["'self'"],
    "object-src": ["'none'"],
    "base-uri": ["'none'"],
    "form-action": ["'self'"],
    "frame-ancestors": ["'none'"],
    "upgrade-insecure-requests": true,
  };

  return buildCSP({ ...base, ...extra });
}
