/**
 * Bundle the built-in presets into the CLI so `--preset <name>` works offline
 * and in the published package (the root `presets/` dir isn't shipped). Reads
 * `presets/*.json` and writes `src/builtin-presets.ts` with the JSON inlined —
 * tsup then compiles it into `dist`. Same generated-module pattern as
 * `templates-map`. Run: `bun run build:presets` (after editing a preset).
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../../..");
const NAMES = ["minimal", "saas-starter", "api-only"] as const;

const entries = NAMES.map((name) => {
  const json = readFileSync(path.join(ROOT, "presets", `${name}.json`), "utf-8").trim();
  return `  ${JSON.stringify(name)}: ${json},`;
}).join("\n");

const out = `// Generated by \`bun run build:presets\` — do not edit by hand.
// Built-in presets bundled into the CLI so \`--preset <name>\` resolves offline.
export const BUILTIN_PRESETS: Record<string, unknown> = {
${entries}
};

export const BUILTIN_PRESET_NAMES = Object.keys(BUILTIN_PRESETS);
`;

writeFileSync(path.join(import.meta.dirname, "../src/builtin-presets.ts"), out);
console.log(`✓ Bundled ${NAMES.length} presets → packages/cli/src/builtin-presets.ts`);
