import { defineAppType } from "./types";

export const sveltekitAppType = defineAppType({
  type: "sveltekit",

  buildPackageJson(_preset, app, { appRefs }) {
    const deps: Record<string, string> = {
      ...appRefs,
    };

    // SvelteKit owns its own tsconfig (generated by `svelte-kit sync`), so
    // it doesn't extend the shared typescript-config package.
    const devDeps: Record<string, string> = {
      "@sveltejs/kit": "catalog:",
      svelte: "catalog:",
      "@sveltejs/adapter-auto": "catalog:",
      "@sveltejs/vite-plugin-svelte": "catalog:",
      "svelte-check": "catalog:",
      vite: "catalog:",
      typescript: "catalog:",
      // SvelteKit's generated tsconfig references node types.
      "@types/node": "catalog:",
    };
    return {
      name: app.name,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: `vite dev --port ${app.port}`,
        build: "vite build",
        preview: "vite preview",
        // `svelte-kit sync` writes .svelte-kit/tsconfig.json + types first.
        prepare: "svelte-kit sync || echo ''",
        "type-check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
      },
      dependencies: deps,
      devDependencies: devDeps,
    };
  },

  buildTsconfig() {
    // Extends the config SvelteKit generates on `sync` (has the $lib alias,
    // svelte types, and the right module settings).
    return {
      extends: "./.svelte-kit/tsconfig.json",
      compilerOptions: {
        allowJs: true,
        checkJs: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        skipLibCheck: true,
        sourceMap: true,
        strict: true,
        moduleResolution: "bundler",
      },
    };
  },
});
